version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
    environment:
      - APP_ENV=development
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
    env_file:
      - .env
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  test:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - APP_ENV=test
      - REDIS_HOST=redis-test
    env_file:
      - .env.test
    depends_on:
      - redis-test
    command: pytest --cov=app --cov-report=html

  redis-test:
    image: redis:7-alpine
    command: redis-server --appendonly no

volumes:
  redis_data:
